os: osx

addons:
    homebrew:
        update: true
        casks:
            - basictex

script:
    - export PATH="$PATH:/Library/TeX/texbin/"
    - make

deploy:
    provider: script
    script: sh deploy.sh
    skip-cleanup: true
    verbose: true
    on:
        tags: true
        branch: master
